# Generated by Django 4.2.6 on 2024-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
